#define LIBXSLT_MAJOR_VERSION 1
#define LIBXSLT_MINOR_VERSION 1
#define LIBXSLT_MICRO_VERSION 34
#define LIBXSLT_DOTTED_VERSION "1.1.34"

#define LIBEXSLT_MAJOR_VERSION 0
#define LIBEXSLT_MINOR_VERSION 8
#define LIBEXSLT_MICRO_VERSION 20
#define LIBEXSLT_DOTTED_VERSION "0.8.20"
